### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [manuelescrig/SuggestionsBox#3]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by manuelescrig** [comment]
I'm planning on doing it in the next couple of weeks. 👍

**Comment by manuelescrig** [comment]
Swift 3 support added in version 1.5

**Comment by lfarah** [comment]
Thanks! 🎉
